Models/AddConta.cs
namespace parteII_pwa_teste.Models;

public class AddConta
{
    public int NumeroDaConta { get; set; }
    public string Titular { get; set; }
    public string Email { get; set; }
}

Models/Domain/Conta.cs
namespace parteII_pwa_teste.Models;

public class Conta
{
    public Guid Id { get; set; }
    public int NumeroDaConta { get; set; }
    public string Titular { get; set; }
    public string Email { get; set; }
}

Models/ErrorViewModel.cs
namespace parteII_pwa_teste.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/UpdateConta.cs
namespace parteII_pwa_teste.Models;

public class UpdateConta
{
    public Guid Id { get; set; }
    public int NumeroDaConta { get; set; }
    public string Titular { get; set; }
    public string Email { get; set; }
}

Controllers/ContaController.cs
using parteII_pwa_teste.Data;
using parteII_pwa_teste.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace parteII_pwa_teste.Controllers {
    public class ContaController : Controller {
        private readonly ContaDBContext contaDbContext;

        public ContaController(ContaDBContext contaDBContext){
            this.contaDbContext = contaDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var contas = await contaDbContext.Contas.ToListAsync();
            return View(contas);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        //CRIA CONTA
        [HttpPost]
        public async Task<IActionResult> Add(AddConta addContaRequest)
        {
            // Cria uma instância da classe Random
            Random random = new();

            // Gere um número aleatório de seis dígitos
            int numeroAleatorio = random.Next(100000, 1000000);
            var conta = new Conta()
            {
                Id = Guid.NewGuid(),
                NumeroDaConta = numeroAleatorio,
                Titular = addContaRequest.Titular,
                Email = addContaRequest.Email,
            };

            await contaDbContext.Contas.AddAsync(conta);
            await contaDbContext.SaveChangesAsync();
            return RedirectToAction("List");
        }

        //MOSTRA OS DETALHES DO CONTA
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var conta = await contaDbContext.Contas.FirstOrDefaultAsync(x => x.Id == id);

            if (conta != null)
            {
                
                var viewModel = new UpdateConta()
                {
                    Id = conta.Id,
                    NumeroDaConta = conta.NumeroDaConta,
                    Titular = conta.Titular,
                    Email = conta.Email,
                };
                return await Task.Run(() => View("Edit", viewModel));
            }

            return RedirectToAction("List");
        }

        //ACTUALIZA O CONTA
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateConta model)
        {
            var conta = await contaDbContext.Contas.FindAsync(model.Id);

            if (conta != null)
            {
                conta.NumeroDaConta = model.NumeroDaConta;
                conta.Titular = model.Titular;
                conta.Email = model.Email;

                await contaDbContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }

        //APAGA CONTA
        [HttpPost]
        public async Task<IActionResult> Delete(UpdateConta model)
        {
            var conta = await contaDbContext.Contas.FindAsync(model.Id);

            if (conta != null)
            {
                contaDbContext.Contas.Remove(conta);
                await contaDbContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using parteII_pwa_teste.Models;

namespace parteII_pwa_teste.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Conta/Add.cshtml
@model parteII_pwa_teste.Models.AddConta

@{
    ViewData["Title"] = "Add Contact";
}

<h1>Adicionar Contacto</h1>
<form action="Add" method="post">
    <div class="mb-3">
        <label for="" class="form-label">Titular</label>
        <input type="text" class="form-control mb-3" placeholder="Jonh Doe" asp-for="Titular">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="email" class="form-control mb-3" placeholder="jonhdoe@gmail.com" asp-for="Email">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>

Views/Conta/Edit.cshtml
@model parteII_pwa_teste.Models.UpdateConta

@{
    ViewData["Title"] = "View";
}

<h1>Editar Contacto</h1>
<form action="Edit" method="post">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control mb-3" placeholder="Jonh" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Número da Conta</label>
        <input type="text" class="form-control mb-3" placeholder="Jonh" asp-for="NumeroDaConta" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Titular</label>
        <input type="text" class="form-control mb-3" placeholder="Jonh" asp-for="Titular">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="email" class="form-control mb-3" placeholder="Doe" asp-for="Email">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Conta">Apagar</button>
</form>

Views/Conta/List.cshtml
@model List<parteII_pwa_teste.Models.Conta>

@{
    ViewData["Title"] = "Edit Page";
}

<h1>Editar Conta</h1>
<div class="text-center">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Número da Conta</th>
                <th scope="col">Titular</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var conta in Model)
            {
                <tr>
                    <th>@conta.Id</th>
                    <td>@conta.NumeroDaConta</td>
                    <td>@conta.Titular</td>
                    <td>@conta.Email</td>
                    <td>
                        <a href="/Conta/Edit/@conta.Id">Editar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Accounts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/parteII_pwa_teste.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Accounts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="List">View Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Add">Add Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Accounts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>